name: Auto-generate

on:
  # æ‰‹åŠ¨è§¦å‘
  workflow_dispatch:
    inputs:
      force_update:
        description: 'å¼ºåˆ¶æ›´æ–°é…ç½®'
        required: false
        default: false
        type: boolean

  # mainåˆ†æ”¯æäº¤è§¦å‘
  push:
    branches:
      - main
    paths:
      - 'Icons/Color/**'
      - 'Icons/scripts/**'
      - 'Clash/Config/*.yaml'
      - 'Clash/Rules/*.yaml'
      - 'Loon/Config/*.lcf'
      - 'Loon/Rules/*.lsr'

# è®¾ç½®æƒé™
permissions:
  contents: read
  pages: write
  id-token: write

# ç¡®ä¿åªæœ‰ä¸€ä¸ªéƒ¨ç½²ä»»åŠ¡åŒæ—¶è¿è¡Œ
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  detect-icons:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: ğŸ“¦ Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: ğŸ—‚ï¸ Create output directory
        run: |
          mkdir -p docs

      - name: ğŸ—ƒï¸ Copy assets files to docs/
        env:
          OUTPUT_DIR: docs
        run: python Icons/scripts/copy_assets_files.py

      - name: ğŸ§  Run grouping script in Icons/
        env:
          OUTPUT_DIR: docs
        run: python Icons/scripts/generate_images_json.py

      - name: ğŸ“ Copy Clash to docs/Clash
        run: rsync -a --exclude='*.md' Clash docs/Clash

      - name: ğŸ“ Copy Loon to docs/Loon
        run: rsync -a --exclude='*.md' Loon docs/Loon

      - name: ğŸ“ Copy Icons/Color to docs/Color
        run: cp -r Icons/Color docs/Color

      - name: ğŸ§± Generate index.html from images.json
        env:
          OUTPUT_DIR: docs
        run: |
          python Icons/scripts/generate_icons_html.py

      - name: ğŸ“¤ Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: detect-icons

    steps:
      - name: â¬†ï¸ Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4